%% Script to generate benchmark config files

% Output File
outPath = 'config/benchmarkReconstructionV1.mat'

%% 3D Reconstruction Parameters
reconstruction = struct(...
    'log', false, ...
    'preprocessing', struct(...
        'scalingFactor', 0.5 ...
    ), ...
    'reconstructionParams', struct(...
        'featureExtraction', struct(...
            'numOctaves', 20, ...
            'roiBorder', 20 ...
        ), ...
        'epipolarGeometry', struct(...
            'eMaxDistance', 5, ...
            'eConfidence', 99.6, ...
            'eMaxNumTrials', 100000, ...
            'eValidPointFraction', 0.8 ...
        ), ...
        'triangulation', struct(...
            'maxReprojectionError', 20 ...
        ) ...
    ) ...
)
%% Save to file
save(outPath, 'reconstruction')