function cameraParams = scaleCameraParameters(cameraParams, scalingFactor, newImageSize)
% SCALECAMERAPARAMETERS Scale camera parameters for a different image size.
% Inputs:
%   cameraParams - cameraParameters object
%   scalingFactor - scale factor
%   newImageSize - new size of the image
% Outputs:
%   cameraParams - scaled cameraParameters object
camIntrinsics = cameraIntrinsics(...
    cameraParams.Intrinsics.FocalLength * scalingFactor, ...
    cameraParams.Intrinsics.PrincipalPoint * scalingFactor,...
    newImageSize, ...
    'RadialDistortion', cameraParams.Intrinsics.RadialDistortion, ...
    'TangentialDistortion', cameraParams.Intrinsics.TangentialDistortion, ...
    'Skew', cameraParams.Intrinsics.Skew);
cameraParams = cameraParameters('K', camIntrinsics.K, 'ImageSize', camIntrinsics.ImageSize);
end